{
  programs.hyprlock = {
    enable = true;
    extraConfig = ''
    source = ~/.cache/wal/hyprlock.conf
  '';

  settings = {
    background = [
      {
        monitor = "";
        color = "$background"; 
        clear_password = true;
      }
    ];

    input-field = [
      {
        monitor = "";
        size = "300, 50";
        outline_thickness = 2;
        dots_size = 0.2;
        dots_spacing = 0.35;
        dots_center = true;

        
        outer_color = "$color4";       
        inner_color = "$background";   
        font_color = "$foreground";    

        fade_on_empty = false;
        rounding = 10; # 

        placeholder_text = "";
        fail_text = "try again...";

        position = "0, -60";
        halign = "center";
        valign = "center";
      }
    ];

    label = [
      {
        monitor = "";
        text = "$TIME";
        color = "$foreground";
        font_size = 64;
        font_family = "Departure Mono";
        position = "0, 80";
        halign = "center";
        valign = "center";
      }
      {
        monitor = "";
        text = "cmd[update:1000] echo -e \"$USER@$HOSTNAME \\n$(date +'%A, %B %d')\"";
        color = "$color7"; 
        font_size = 14;
        font_family = "Departure Mono";
        position = "0, 10";
        halign = "center";
        valign = "center";
      }
    ];
  };
  };

  home.file.".config/wal/templates/hyprlock.conf".text = ''
  # Hyprlock color definitions generated by pywal via Nix
  $background = rgb({background.strip})
  $foreground = rgb({foreground.strip})

  $color0 = rgb({color0.strip})
  $color1 = rgb({color1.strip})
  $color2 = rgb({color2.strip})
  $color3 = rgb({color3.strip})
  $color4 = rgb({color4.strip})
  $color5 = rgb({color5.strip})
  $color6 = rgb({color6.strip})
  $color7 = rgb({color7.strip})
  $color8 = rgb({color8.strip})
  $color9 = rgb({color9.strip})
  $color10 = rgb({color10.strip})
  $color11 = rgb({color11.strip})
  $color12 = rgb({color12.strip})
  $color13 = rgb({color13.strip})
  $color14 = rgb({color14.strip})
  $color15 = rgb({color15.strip})
'';

}